parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\:
        resource: '../src/App/Controller/'
        autowire: true
        tags: ['controller.service_arguments']

    App\ExchangeRates\Infrastructure\Adapter\:
        resource: '../src/App/ExchangeRates/Infrastructure/Adapter/'
        tags: [ 'controller.service_arguments' ]

    App\ExchangeRates\Application\Service\:
        resource: '../src/App/ExchangeRates/Application/Service/'
        tags: [ 'controller.service_arguments' ]

    App\ExchangeRates\Domain\Port\ExchangeRateProvider:
        class: App\ExchangeRates\Infrastructure\Adapter\NBPExchangeRateAdapter

    App\ExchangeRates\Domain\Profit\ProfitManager:
        class: App\ExchangeRates\Domain\Profit\ProfitManagerImpl
